version: "3.9"
services:
  db:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "defaultdb"
      POSTGRES_USER: "primakov127"
      POSTGRES_PASSWORD: "primakov127"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
    ports:
      - "5432:5432"
